### ISSUE TITLE
feature request: support for Victoria Day

### ISSUE THREAD

**Issue by bcrowell** [bcrowell/when#28]
Victoria Day in Canada is the last Monday before May 25. Currently, when doesn't have any way to handle this. It would be nice to have a feature that could make this work. A possibility would be to have a unary function that would compute the difference in days between the present date and a fixed day-month. I'm not motivated enough to code this up myself, because I don't think it would be a straightforward modification to the parser, but I would be happy to accept a patch. Maybe the syntax could be like fn_days(may 25). The test for Victoria Day would then be (fn_days(may 25) > -8) & (fn_days(may 25) < 0) & (w=mon).

**Comment by audiofool** [comment]
Nice work!  I have been using 'remind' but find it over complicated for my needs and would like to replace it with 'when'.  Here is what I did for Victoria Day:
m=may & w=mon & (d>=18 & d<=24) ,Victoria Day

Questions:
1. m=sep & w=mon & a=1 -> prints blank 4 instead of leading zero, 04
2. I also would like to show new and full moons, any ideas? or would this need to be an enhancement?
3. c= option works great for US in Canada most fed holidays default to Monday if on Sat or Sun, maybe f= for Canada?

Thanks again

**Comment by bcrowell** [comment]
Thanks for the suggestion on how to handle Victoria Day! I've added that to the documentation.

1. This is the intended behavior, for alignment.
2. This is out of the scope of the software.
3. You should be able to do this with an "or" for the three cases, where the holiday falls on Sat, Sun, or some other day.

**Comment by audiofool** [comment]
Not sure if I explained it right:
  * jan 01 ,test               =>   2022 Jan 01 test
   m=jan & d=01 ,test   =>    2022 Jan   1 test
